#!/usr/bin/env bash

# Copyright (c) 2024-2026 QBiz Contributors
# License: MIT
# Source: https://github.com/ardianryan/qbiz-qrisdinamis

source /dev/stdin <<< "$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

msg_info "Installing Base Dependencies"
$STD apt-get install -y \
  curl \
  sudo \
  mc \
  git \
  ca-certificates \
  gnupg \
  unzip \
  openssl
msg_ok "Installed Base Dependencies"

msg_info "Installing Chromium and Graphic Libraries (Puppeteer Support)"
$STD apt-get install -y \
  chromium \
  fonts-liberation \
  fonts-noto-color-emoji \
  libnss3 \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libdrm2 \
  libxkbcommon0 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  libgbm1 \
  libasound2
msg_ok "Installed Chromium and Graphic Libraries"

msg_info "Installing PostgreSQL Server"
$STD apt-get install -y postgresql postgresql-contrib
systemctl enable --now postgresql
msg_ok "Installed PostgreSQL Server"

msg_info "Configuring PostgreSQL Database and User"
DB_PASS=$(openssl rand -hex 16)
sudo -u postgres psql -c "CREATE USER qbiz WITH PASSWORD '${DB_PASS}';" >/dev/null 2>&1 || true
sudo -u postgres psql -c "ALTER USER qbiz WITH PASSWORD '${DB_PASS}';" >/dev/null 2>&1 || true
sudo -u postgres psql -c "CREATE DATABASE qbiz OWNER qbiz;" >/dev/null 2>&1 || true
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE qbiz TO qbiz;" >/dev/null 2>&1 || true
msg_ok "Configured PostgreSQL (Database: qbiz, User: qbiz)"

msg_info "Installing Deno Runtime"
export DENO_INSTALL="/usr/local"
curl -fsSL https://deno.land/install.sh | $STD sh -s -- -y
chmod 755 /usr/local/bin/deno
msg_ok "Installed Deno Runtime ($(deno --version | head -n1))"

msg_info "Deploying QBiz Gateway Hub"
if [ -d "/opt/qbiz" ]; then
  rm -rf /opt/qbiz
fi
$STD git clone https://github.com/ardianryan/qbiz-qrisdinamis.git /opt/qbiz

COOKIE_SECRET=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)

cat <<EOF > /opt/qbiz/.env
# QBiz Production Configuration (Generated by Proxmox VE Helper)
PORT=8000
DATABASE_URL=postgresql://qbiz:${DB_PASS}@localhost:5432/qbiz
COOKIE_SECRET=${COOKIE_SECRET}
JWT_SECRET=${JWT_SECRET}
PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
DENO_ENV=production
EOF

chmod 600 /opt/qbiz/.env
msg_ok "Deployed QBiz to /opt/qbiz"

msg_info "Pre-caching Deno Dependencies"
cd /opt/qbiz
$STD deno cache main.tsx
msg_ok "Pre-cached Deno Dependencies"

msg_info "Creating Systemd Service"
cat <<EOF > /etc/systemd/system/qbiz.service
[Unit]
Description=QBiz Payment Gateway Hub
Documentation=https://github.com/ardianryan/qbiz-qrisdinamis
After=network.target postgresql.service
Wants=postgresql.service

[Service]
Type=simple
User=root
WorkingDirectory=/opt/qbiz
EnvironmentFile=/opt/qbiz/.env
ExecStart=/usr/local/bin/deno run -A --env /opt/qbiz/main.tsx
Restart=always
RestartSec=5
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now qbiz.service
msg_ok "Created and Started QBiz Service"

motd_ssh
customize

msg_info "Cleaning up"
$STD apt-get -y autoremove
$STD apt-get -y autoclean
msg_ok "Cleaned up"
