#!/usr/bin/env bash

# Copyright (c) 2024-2026 QBiz Contributors
# License: MIT
# Source: https://github.com/ardianryan/qbiz-qrisdinamis

source /dev/stdin <<< "$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

msg_info "Installing Base Dependencies"
$STD apt-get install -y \
  whiptail \
  curl \
  sudo \
  mc \
  git \
  ca-certificates \
  gnupg \
  unzip \
  openssl
msg_ok "Installed Base Dependencies"

msg_info "Installing Chromium and Graphic Libraries (Puppeteer Support)"
$STD apt-get install -y \
  chromium \
  fonts-liberation \
  fonts-noto-color-emoji \
  libnss3 \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libdrm2 \
  libxkbcommon0 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  libgbm1 \
  libasound2
msg_ok "Installed Chromium and Graphic Libraries"

# Interactive Database Architecture Selection
DB_CHOICE="local"
EXT_DB_URL=""
if command -v whiptail >/dev/null 2>&1; then
  DB_CHOICE=$(whiptail --backtitle "QBiz Gateway Hub LXC Installer" \
    --title "Database Configuration" \
    --radiolist "Choose your PostgreSQL database backend:\n(Use Spacebar to toggle selection, Enter to confirm)" 14 74 2 \
    "local" "Local PostgreSQL (All-in-One server inside container)" ON \
    "external" "External PostgreSQL (Supabase, Neon, Cloud, or Remote VM)" OFF \
    3>&1 1>&2 2>&3) || DB_CHOICE="local"
fi

if [ "$DB_CHOICE" == "external" ]; then
  if command -v whiptail >/dev/null 2>&1; then
    EXT_DB_URL=$(whiptail --backtitle "QBiz Gateway Hub LXC Installer" \
      --title "External PostgreSQL Connection URI" \
      --inputbox "Enter your remote PostgreSQL Connection URI:\n(e.g., postgresql://postgres.xxx:password@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres)\n\nLeave blank to configure manually later in /opt/qbiz/.env:" 14 80 \
      3>&1 1>&2 2>&3) || EXT_DB_URL=""
  fi
fi

if [ "$DB_CHOICE" == "local" ]; then
  msg_info "Installing Local PostgreSQL Server"
  $STD apt-get install -y postgresql postgresql-contrib
  systemctl enable --now postgresql
  msg_ok "Installed Local PostgreSQL Server"

  msg_info "Configuring Local PostgreSQL Database and User"
  DB_PASS=$(openssl rand -hex 16)
  sudo -u postgres psql -c "CREATE USER qbiz WITH PASSWORD '${DB_PASS}';" >/dev/null 2>&1 || true
  sudo -u postgres psql -c "ALTER USER qbiz WITH PASSWORD '${DB_PASS}';" >/dev/null 2>&1 || true
  sudo -u postgres psql -c "CREATE DATABASE qbiz OWNER qbiz;" >/dev/null 2>&1 || true
  sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE qbiz TO qbiz;" >/dev/null 2>&1 || true
  DATABASE_URL="postgresql://qbiz:${DB_PASS}@localhost:5432/qbiz"
  SYSTEMD_DB_DEP="After=network.target postgresql.service\nWants=postgresql.service"
  msg_ok "Configured Local PostgreSQL (Database: qbiz, User: qbiz)"
else
  msg_info "Configuring External PostgreSQL Database"
  if [ -n "$EXT_DB_URL" ]; then
    DATABASE_URL="$EXT_DB_URL"
    msg_ok "Configured External Database URI"
  else
    DATABASE_URL="postgresql://postgres:PASSWORD@YOUR_REMOTE_HOST:5432/postgres"
    msg_ok "Set placeholder DATABASE_URL (configure later in /opt/qbiz/.env)"
  fi
  SYSTEMD_DB_DEP="After=network.target"
fi

msg_info "Installing Deno Runtime"
export DENO_INSTALL="/usr/local"
curl -fsSL https://deno.land/install.sh | $STD sh -s -- -y
chmod 755 /usr/local/bin/deno
msg_ok "Installed Deno Runtime ($(deno --version | head -n1))"

msg_info "Deploying QBiz Gateway Hub"
if [ -d "/opt/qbiz" ]; then
  rm -rf /opt/qbiz
fi
$STD git clone https://github.com/ardianryan/qbiz-qrisdinamis.git /opt/qbiz

COOKIE_SECRET=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)

cat <<EOF > /opt/qbiz/.env
# QBiz Production Configuration (Generated by Proxmox VE Helper)
PORT=8000
DATABASE_URL=${DATABASE_URL}
COOKIE_SECRET=${COOKIE_SECRET}
JWT_SECRET=${JWT_SECRET}
PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
DENO_ENV=production
EOF

chmod 600 /opt/qbiz/.env
msg_ok "Deployed QBiz to /opt/qbiz"

msg_info "Pre-caching Deno Dependencies"
cd /opt/qbiz
$STD deno cache main.tsx
msg_ok "Pre-cached Deno Dependencies"

if [ "$DB_CHOICE" == "local" ] || [ -n "$EXT_DB_URL" ]; then
  msg_info "Initializing Database Schema Migrations"
  cd /opt/qbiz
  $STD deno task db:migrate || true
  msg_ok "Initialized Database Schema"
else
  msg_info "Skipping initial schema migration (external DATABASE_URL not yet configured)"
fi

msg_info "Creating Systemd Service"
cat <<EOF > /etc/systemd/system/qbiz.service
[Unit]
Description=QBiz Payment Gateway Hub
Documentation=https://github.com/ardianryan/qbiz-qrisdinamis
$(echo -e "${SYSTEMD_DB_DEP}")

[Service]
Type=simple
User=root
WorkingDirectory=/opt/qbiz
EnvironmentFile=/opt/qbiz/.env
ExecStart=/usr/local/bin/deno run -A --env /opt/qbiz/main.tsx
Restart=always
RestartSec=5
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now qbiz.service
msg_ok "Created and Started QBiz Service"

msg_info "Installing In-Container Update Helper"
chmod +x /opt/qbiz/proxmox/update.sh
ln -sf /opt/qbiz/proxmox/update.sh /usr/local/bin/update
msg_ok "Configured 'update' command in /usr/local/bin/update"

motd_ssh
customize

msg_info "Cleaning up"
$STD apt-get -y autoremove
$STD apt-get -y autoclean
msg_ok "Cleaned up"
